version: '3.8'

services:
  nginx-task-one:
    image: nginx:latest
    container_name: nginx-task-one
    ports:
      - "8686:80"
    restart: unless-stopped
    volumes:
      # Это файлы сайтов
      - ./app:/usr/share/nginx/html
      # Файлы логов
      - ./logs:/var/log/nginx
