version: "3.8"

networks:
  task:
    driver: bridge

volumes:
  task-mysql:

services:
  php-fpm:
    image: docker.io/bitnami/php-fpm:latest
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    networks:
      - task

  nginx:
    image: nginx:latest
    container_name: nginx_task
    restart: unless-stopped
    ports:
      - "8701:80"
    volumes:
      # Это конфиги для хостов
      - ./nginx-config:/etc/nginx/conf.d
      # Это файлы сайтов
      - ./app:/var/www/html
      - ./logs:/var/log/nginx
    networks:
      - task

  mysql:
    image: mysql:latest
    container_name: mysql-server_task
    restart: always
    ports:
      - 8702:3306
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dump-task:/docker-entrypoint-initdb.d
      - task-mysql:/var/lib/mysql
    networks:
      - task

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_task
    restart: always
    ports: 
      - 8703:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - task

  adminer:
    image: adminer:latest
    container_name: db_adminer_task
    restart: always
    ports:
      - 8704:8080
    networks:
      - task